version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: qforge-api-prod
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: always
    # We use network_mode: host here for extreme simplicity on EC2, 
    # so the API can talk to localhost:2000 (Piston Sandbox) exactly as it does locally
    network_mode: host
